// <auto-generated />
using ATMApp.DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATMApp.Migrations
{
    [DbContext(typeof(ATMAppContext))]
    [Migration("20230503100054_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATMApp.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountBalance = 0m,
                            AccountNo = "null",
                            FirstName = "null",
                            LastName = "null",
                            Password = "null"
                        },
                        new
                        {
                            Id = 2,
                            AccountBalance = 25000m,
                            AccountNo = "10000001",
                            FirstName = "Fatih",
                            LastName = "Can",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 3,
                            AccountBalance = 45000m,
                            AccountNo = "10000002",
                            FirstName = "Yusuf",
                            LastName = "Asaf",
                            Password = "4321"
                        },
                        new
                        {
                            Id = 4,
                            AccountBalance = 5000m,
                            AccountNo = "10000003",
                            FirstName = "Ahmet",
                            LastName = "Can",
                            Password = "1111"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
